// Mocks generated by Mockito 5.0.15 from annotations
// in app_movie/test/features/data/repository/MovieRepositoryImpl_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:app_movie/features/data/datasource/MovieRemoteDataSource.dart'
    as _i3;
import 'package:app_movie/features/data/models/MovieModel.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

class _FakeMovieModel_0 extends _i1.Fake implements _i2.MovieModel {}

/// A class which mocks [MovieRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockMovieRemoteDataSource extends _i1.Mock
    implements _i3.MovieRemoteDataSource {
  MockMovieRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.MovieModel> getmovieDetails(int? id) =>
      (super.noSuchMethod(Invocation.method(#getmovieDetails, [id]),
              returnValue: Future<_i2.MovieModel>.value(_FakeMovieModel_0()))
          as _i4.Future<_i2.MovieModel>);
  @override
  String toString() => super.toString();
}
