// Mocks generated by Mockito 5.0.15 from annotations
// in app_movie/test/features/data/repository/MovieRepositoryImpl_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:app_movie/features/data/datasource/MovieRemoteDataSourceImpl.dart'
    as _i3;
import 'package:http/http.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

class _FakeClient_0 extends _i1.Fake implements _i2.Client {}

/// A class which mocks [MovieRemoteDataSourceImpl].
///
/// See the documentation for Mockito's code generation for more information.
class MockMovieRemoteDataSourceImpl extends _i1.Mock
    implements _i3.MovieRemoteDataSourceImpl {
  MockMovieRemoteDataSourceImpl() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Client get client => (super.noSuchMethod(Invocation.getter(#client),
      returnValue: _FakeClient_0()) as _i2.Client);
  @override
  _i4.Future<dynamic> getmovieDetails(int? id) =>
      (super.noSuchMethod(Invocation.method(#getmovieDetails, [id]),
          returnValue: Future<dynamic>.value()) as _i4.Future<dynamic>);
  @override
  String toString() => super.toString();
}
